export { getPeopleById, getAllPeople, getPeopleByPage } from './people'
export { getPlanetsById, getAllPlanets, getPlanetsByPage } from './planet'
export { getAllSpecies, getSpeciesByPage, getSpeciesById } from './species'
export { getStarshipsById, getAllStarships, getStarshipsByPage } from './starship'
export { getFilmsByPage, getAllFilms, getFilmsById } from './films'
export { getAllVehicles, getVehiclesByPage, getVehiclesById } from './vehicles'
